### ISSUE TITLE
Add locator user setting to allow setting a country code in the query

### ISSUE THREAD

**Issue by palmerj** [rduivenvoorde/nominatim_locator_filter#6]
e.g https://nominatim.openstreetmap.org/ui/search.html?q=84+Tio+Tio+Road&countrycodes=nz

**Comment by OSHistory** [comment]
This would be nice, indeed. However it would be to determined where such a setting would be registered in the UI. 

According to the [API](https://nominatim.org/release-docs/develop/api/Search/) a combination of query and structured 
parameters (as country codes is not supported): 

> Alternative query string format split into several parameters for structured requests. Structured requests are faster but are less robust against alternative OSM tagging schemas. Do not combine with q=<query> parameter.

The only alternative would be an extended address output via `addressdetails`, e.g. 

https://nominatim.openstreetmap.org/search?format=json&q=Bonn&addressdetails=1

The Plugin could check the countryCode *after* the fact, clearing out all results not matching the country code. 

This could be done by allowing for a query-String ending in `:de`, `:gb` etc. once an ISO-Country Code is requested, the 
results from nominatim would be filtered before displaying them. So instead of `Bonn ` you would search for `Bonn:de `

@rduivenvoorde Is that be something you would be interested? I could look into an implementation an do a PR (no promises on the timeline, though).

**Comment by rduivenvoorde** [comment]
I'm not sure if we want to create some kind of query language just for one locator. Note we are not the only 'locator'.

About countrycods: the q-form already works like this I think: if you search for `84+Tio+Tio ` you will end up in Chili, but addin `nz ` to it you will end up in Wellington.

Do you think filtering clientside would work better?

**Comment by OSHistory** [comment]
Thanks for the fast reply. Indeed, adding the country code via '+' does restrict the search via the query. I was not aware of that. Maybe something to share in the `README.md`. A programmatic approach as described above would not be necessary.

**Comment by rduivenvoorde** [comment]
Ok added this info the the README and information which is shown in the plugin dialog (of the next version). So closing this one.
